# golangci-lint configuration for pguard
# Run: golangci-lint run ./...

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Tier 1: Essential - catch real bugs
    - errcheck       # Unchecked errors
    - govet          # Go vet checks
    - staticcheck    # Comprehensive static analysis
    - unused         # Unused code
    - gosimple       # Simplification suggestions
    - ineffassign    # Ineffective assignments

    # Tier 2: Recommended - code quality
    - revive         # Style checks (golint replacement)
    - misspell       # Spelling mistakes in comments/strings
    - goimports      # Import organization
    - gocritic       # Extensive code checks

    # Tier 3: Project-specific
    - forbidigo      # Forbid fmt.Print (use slog)

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow `_ = something`

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too pedantic for most projects

  revive:
    rules:
      - name: unused-parameter
        disabled: true  # Noisy in tests with http.Handler signatures
      - name: var-naming
        disabled: false
      - name: exported
        disabled: false

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam        # Too strict for this project
      - rangeValCopy     # Often false positives

  misspell:
    locale: US

  forbidigo:
    forbid:
      - p: ^fmt\.Print.*$
        msg: use slog for logging instead of fmt.Print

  goimports:
    local-prefixes: github.com/v0xg/pg-idle-guard

issues:
  exclude-rules:
    # Allow fmt.Print in tests
    - path: _test\.go
      linters:
        - forbidigo

    # Allow fmt.Print in CLI commands (user prompts, output formatting)
    - path: cli/(configure|kill|status|watch|root)\.go
      linters:
        - forbidigo

    # Allow longer functions in tests
    - path: _test\.go
      linters:
        - gocritic
      text: "hugeParam"
